version: 2
jobs:
  build:
    docker:
    -
      image: circleci/node:10.12

    steps:
    -
      checkout:
        name: Checking out

    -
      restore_cache:
        name: Restoring node_modules cache
        key: v1-dependencies-{{ checksum "package.json" }}

    -
      run:
        name: Installing modules
        command: npm install

    -
      save_cache:
        name: Saving node_modules cache
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      
    -
      run:
        name: Testing
        command: npm test

    -
      run:
        name: Running
        command: npm start
    
    -
      run:
        name: Preparing artifacts
        command: |
          rm -rf artifacts/
          mkdir artifacts/
          mv output.* artifacts/
    
    -
      store_artifacts:
        path: ./artifacts/
        destination: output